name: "Action di Treminio"
on:
  push:
jobs:
  ciao: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "ciao sono una stringa"
      - run: echo "ciao sono una stringa 2" 
      - run: echo "python è bello"
      - run : pip --version
      - run: ls -la
      - run: pwd
      - run: env
      - uses: actions/checkout@v4
        with:
          sparse-checkout:
            treminio
      - run: ls -la
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python --version
      - run: pip install -r requirements.txt
        working-directory: treminio
      - run: python train_direc.py
        working-directory: treminio 