name: "Action di Treminio"
on:
  push:
jobs:
  ciao: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "ciao sono una stringa"
      - run: echo "ciao sono una stringa 2" 
      - run: echo "python è bello"